[package]
name = "tauri-plugin-stt"
version = "0.1.0"
authors = ["Affex Team"]
description = "Speech-to-text recognition plugin for Tauri with multi-language support"
edition = "2021"
rust-version = "1.77.2"
license = "MIT"
repository = "https://github.com/brenogonzaga/tauri-plugin-stt"
homepage = "https://github.com/brenogonzaga/tauri-plugin-stt"
documentation = "https://docs.rs/tauri-plugin-stt"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-stt"
keywords = ["tauri", "speech", "recognition", "stt", "vosk"]
categories = ["multimedia::audio", "api-bindings"]

[dependencies]
tauri = { version = "2.9.5" }
serde = "1.0"
thiserror = "2"
serde_json = "1.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
cpal = "0.15"
vosk = "0.3"
reqwest = { version = "0.12", features = ["blocking"] }
zip = "6.0.0"
md-5 = "0.10"


[build-dependencies]
tauri-plugin = { version = "2.5.2", features = ["build"] }
